name: release_script
description: A tool for releasing dart apps
version: 0.0.1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  args: ^2.3.1
  built_collection: ^5.1.1
  built_value: ^8.3.3
  pub_semver: ^2.1.1

dev_dependencies:
  built_value_generator: ^8.3.3
  build_runner: ^2.1.11
  lints: ^2.0.0
  meta: ^1.8.0
