name: Sanity Check
on: [push]
jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Flutter Setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.4"
      - name: Fetch Packages
        run: flutter pub get
      - name: Show environment
        run: env
      - name: Lint
        run: flutter analyze
      - name: Test with Coverage
        run: flutter test --coverage
      - name: Clean up coverage
        run: flutter pub run remove_from_coverage -f coverage/lcov.info -r '\.g\.dart$' -r 'main\.dart' -r 'constants\.dart'
      - name: Update Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
